model: diffusion_gan
dataset: fashionmnist
res: 64
batch_size: 32
channels: 3
dim_w: 512
mappingnet_layers: 8
epochs: 30
lr: 1e-3
mapping_lr: 1e-5
mixing_prob: 0.9
grad_pen_interval: 32
grad_pen_coef: 10
path_pen_interval: 32
path_pen_after: 5000
t_update_interval: 4
d_target: 0.6
update_kimg: 100
device: cpu
save_dir: ./results/diff_gan/