model: stylegan2
dataset: stl10
res: 64
batch_size: 32
channels: 3
dim_w: 512
mappingnet_layers: 8
epochs: 30
lr: 1e-3
mapping_lr: 1e-5
mixing_prob: 0.9
grad_pen_interval: 32
grad_pen_coef: 10
path_pen_interval: 32
path_pen_after: 5000
device: cpu
save_dir: ./results/stylegan2/